package router

import (
	"github.com/gin-gonic/gin"
	"github.com/hdu-dp/backend/internal/handlers"
	adminHandlers "github.com/hdu-dp/backend/internal/handlers/admin"
	"github.com/hdu-dp/backend/internal/middleware"

	_ "github.com/hdu-dp/backend/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// Params groups dependencies required for routing.
type Params struct {
	Engine             *gin.Engine
	AuthMiddleware     *middleware.AuthMiddleware
	AuthHandler        *handlers.AuthHandler
	UserHandler        *handlers.UserHandler
	ReviewHandler      *handlers.ReviewHandler
	StoreHandler       *handlers.StoreHandler
	ReviewStoreHandler *handlers.ReviewStoreHandler
	AdminHandler       *adminHandlers.ReviewAdminHandler
	StoreAdminHandler  *adminHandlers.StoreAdminHandler
	StaticUploadDir    string
}

// Register configures API routes on the provided engine.
func Register(p Params) {
	p.Engine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	api := p.Engine.Group("/api/v1")

	auth := api.Group("/auth")
	{
		auth.POST("/register", p.AuthHandler.Register)
		auth.POST("/login", p.AuthHandler.Login)
		auth.POST("/refresh", p.AuthHandler.Refresh)
		auth.POST("/logout", p.AuthHandler.Logout)
	}

	if p.StaticUploadDir != "" {
		api.Static("/uploads", p.StaticUploadDir)

		p.Engine.NoRoute(func(c *gin.Context) {
			// For any unhandled API routes, return a standard JSON 404 error.
			c.JSON(404, gin.H{"error": "not found"})
		})
	}

	api.GET("/reviews", p.ReviewHandler.ListPublic)
	// Detail endpoint should be accessible to authed/unauthed; optional auth ensures role-based access when provided.
	api.GET("/reviews/:id", p.AuthMiddleware.OptionalAuth(), p.ReviewHandler.Detail)

	protected := api.Group("")
	protected.Use(p.AuthMiddleware.RequireAuth())
	{
		protected.GET("/users/me", p.UserHandler.Me)

		protected.POST("/reviews", p.ReviewHandler.Submit)
		protected.GET("/reviews/me", p.ReviewHandler.MyReviews)
		protected.POST("/reviews/:id/images", p.ReviewHandler.UploadImage)
	}

	// 店铺相关接口（公开）
	stores := api.Group("/stores")
	{
		stores.GET("", p.StoreHandler.SearchStores)
		stores.GET("/:id", p.StoreHandler.GetStore)
	}

	// 店铺相关接口（需要认证）
	protectedStores := api.Group("")
	protectedStores.Use(p.AuthMiddleware.RequireAuth())
	{
		protectedStores.GET("/stores/:id/my-review", p.StoreHandler.GetMyReview)
		protectedStores.POST("/stores/with-review", p.StoreHandler.CreateStoreWithReview)
		protectedStores.POST("/reviews/store", p.ReviewStoreHandler.SubmitReview)
		protectedStores.PUT("/reviews/store/:id", p.ReviewStoreHandler.UpdateReview)
		protectedStores.GET("/stores/:id/reviews", p.ReviewStoreHandler.GetStoreReviews)
	}

	// 管理员接口
	admin := api.Group("/admin")
	admin.Use(p.AuthMiddleware.RequireAuth(), p.AuthMiddleware.RequireRoles("admin"))
	{
		// 评价管理
		admin.GET("/reviews/pending", p.AdminHandler.Pending)
		admin.PUT("/reviews/:id/approve", p.AdminHandler.Approve)
		admin.PUT("/reviews/:id/reject", p.AdminHandler.Reject)
		admin.DELETE("/reviews/:id", p.AdminHandler.Delete)

		// 店铺管理
		admin.GET("/stores/pending", p.StoreAdminHandler.Pending)
		admin.PUT("/stores/:id/approve", p.StoreAdminHandler.Approve)
		admin.PUT("/stores/:id/reject", p.StoreAdminHandler.Reject)
		admin.DELETE("/stores/:id", p.StoreAdminHandler.Delete)
	}
}
