// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/reviews/pending": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取等待管理员审核的点评列表，支持分页、搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "待审核点评列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-created_at",
                        "description": "排序字段 (e.g., -created_at, rating)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ReviewListResult"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/reviews/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "永久删除指定 ID 的点评及其关联的图片。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "删除点评",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点评 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "无效的点评 ID",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "点评不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/reviews/{id}/approve": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "将指定 ID 的点评状态标记为“已批准”。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "批准点评",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点评 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批准成功",
                        "schema": {
                            "$ref": "#/definitions/models.Review"
                        }
                    },
                    "400": {
                        "description": "无效的点评 ID 或状态错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "点评不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/reviews/{id}/reject": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "将指定 ID 的点评状态标记为“已拒绝”，并记录原因。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理"
                ],
                "summary": "拒绝点评",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点评 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "拒绝原因",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "拒绝成功",
                        "schema": {
                            "$ref": "#/definitions/models.Review"
                        }
                    },
                    "400": {
                        "description": "无效的点评 ID 或请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "点评不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/stores": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "管理员直接创建一个已审核通过的店铺。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员 - 店铺"
                ],
                "summary": "创建新店铺",
                "parameters": [
                    {
                        "description": "店铺信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "409": {
                        "description": "店铺已存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/stores/pending": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取待审核的店铺列表，支持分页。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员 - 店铺"
                ],
                "summary": "待审核店铺列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.StoreListResult"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/stores/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "管理员删除指定的店铺（包含关联的评价和图片记录）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员 - 店铺"
                ],
                "summary": "删除店铺",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功"
                    },
                    "404": {
                        "description": "店铺不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/stores/{id}/approve": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "管理员审核通过指定的店铺。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员 - 店铺"
                ],
                "summary": "审核通过店铺",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的店铺",
                        "schema": {
                            "$ref": "#/definitions/models.Store"
                        }
                    },
                    "400": {
                        "description": "店铺已被处理",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "店铺不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/admin/stores/{id}/reject": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "管理员驳回指定的店铺并填写原因。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员 - 店铺"
                ],
                "summary": "驳回店铺",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "驳回原因",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "reason": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的店铺",
                        "schema": {
                            "$ref": "#/definitions/models.Store"
                        }
                    },
                    "400": {
                        "description": "店铺已被处理",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "店铺不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "接收用户邮箱和密码进行登录，成功后返回认证信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "refresh_token": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "display_name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "role": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "邮箱或密码错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "接收刷新令牌并使其失效。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "登出成功"
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "无效的刷新令牌",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "使用有效的刷新令牌获取新的访问令牌和刷新令牌。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新令牌",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "refresh_token": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "display_name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "role": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "无效的刷新令牌",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "接收用户邮箱、密码和昵称进行注册，成功后返回认证信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "display_name": {
                                    "type": "string"
                                },
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "refresh_token": {
                                    "type": "string"
                                },
                                "user": {
                                    "type": "object",
                                    "properties": {
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "display_name": {
                                            "type": "string"
                                        },
                                        "email": {
                                            "type": "string"
                                        },
                                        "id": {
                                            "type": "integer"
                                        },
                                        "role": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "409": {
                        "description": "邮箱已被占用",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/reviews": {
            "get": {
                "description": "获取已审核通过的点评列表，支持分页、搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点评"
                ],
                "summary": "公开点评列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-created_at",
                        "description": "排序字段 (e.g., -created_at, rating)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ReviewListResult"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建一个新的评价。如果提供了 ` + "`" + `autoCreateStore=true` + "`" + ` 查询参数，则会在店铺不存在时自动创建店铺。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点评"
                ],
                "summary": "创建新评价",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "是否在店铺不存在时自动创建",
                        "name": "autoCreateStore",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "幂等键 (UUID)，用于防止重复提交",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "评价和新店铺信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReviewForNewStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "409": {
                        "description": "用户已评价过该店铺",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "429": {
                        "description": "请求正在处理中",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/reviews/{id}": {
            "get": {
                "description": "根据 ID 获取单个点评的详细信息。未审核的点评仅作者和管理员可见。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点评"
                ],
                "summary": "获取点评详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点评 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "无效的点评 ID",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "403": {
                        "description": "无权访问",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "点评不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/reviews/{id}/images": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定的点评上传一张图片。用户只能为自己的点评上传。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "点评"
                ],
                "summary": "上传点评图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "点评 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "上传成功",
                        "schema": {
                            "$ref": "#/definitions/models.ReviewImage"
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "点评不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/stores": {
            "get": {
                "description": "根据多种条件搜索已审核通过的店铺，支持分页、排序和过滤。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "搜索店铺",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词 (名称或地址)",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-created_at",
                        "description": "排序字段 (e.g., -created_at, average_rating)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "店铺分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "店铺状态 (仅管理员可用)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.StoreListResult"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户创建一个新的店铺，需要等待管理员审核。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "创建新店铺",
                "parameters": [
                    {
                        "description": "店铺信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "409": {
                        "description": "店铺已存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/stores/{id}": {
            "get": {
                "description": "根据 ID 获取单个店铺的详细信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "获取店铺详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "店铺详情",
                        "schema": {
                            "$ref": "#/definitions/dto.StoreResponse"
                        }
                    },
                    "400": {
                        "description": "无效的店铺 ID",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "店铺不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/stores/{id}/reviews": {
            "get": {
                "description": "获取指定店铺下所有已审核通过的评价。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "获取店铺的评价列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-created_at",
                        "description": "排序字段 (e.g., -created_at, rating)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ReviewListResult"
                        }
                    },
                    "400": {
                        "description": "无效的店铺 ID",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "为指定店铺提交一条新评价。支持通过 ` + "`" + `?autoCreate=true` + "`" + ` 在评价时自动创建不存在的店铺。该接口支持通过 ` + "`" + `Idempotency-Key` + "`" + ` 请求头实现幂等性。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "提交店铺评价",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID (当 autoCreate=false 时)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "是否在店铺不存在时自动创建",
                        "name": "autoCreate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "幂等键 (UUID)，用于防止重复提交",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "评价内容 (当 autoCreate=false)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReviewRequest"
                        }
                    },
                    {
                        "description": "评价和新店铺信息 (当 autoCreate=true)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateReviewForNewStoreRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "409": {
                        "description": "用户已评价过该店铺",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "429": {
                        "description": "请求正在处理中",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/stores/{id}/reviews/{reviewId}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除用户对指定店铺的评价。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "删除店铺评价",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评价 ID",
                        "name": "reviewId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功"
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "评价不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新用户对指定店铺的评价。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "店铺"
                ],
                "summary": "更新店铺评价",
                "parameters": [
                    {
                        "type": "string",
                        "description": "店铺 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "评价 ID",
                        "name": "reviewId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "要更新的评价内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "403": {
                        "description": "无权操作",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "评价不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前已认证用户的详细信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "created_at": {
                                    "type": "string"
                                },
                                "display_name": {
                                    "type": "string"
                                },
                                "email": {
                                    "type": "string"
                                },
                                "id": {
                                    "type": "integer"
                                },
                                "role": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "未认证",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        },
        "/users/me/reviews": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前认证用户提交的所有点评列表，支持分页、搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "我的点评列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "-created_at",
                        "description": "排序字段 (e.g., -created_at, rating)",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.ReviewListResult"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/problem.Details"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthorResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.CreateReviewForNewStoreRequest": {
            "type": "object",
            "required": [
                "content",
                "rating",
                "store_address",
                "store_name",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "rating": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0
                },
                "store_address": {
                    "type": "string"
                },
                "store_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.CreateReviewRequest": {
            "type": "object",
            "required": [
                "content",
                "rating",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "rating": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.CreateStoreRequest": {
            "type": "object",
            "required": [
                "address",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.ImageResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.ReviewResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/dto.AuthorResponse"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ImageResponse"
                    }
                },
                "rating": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "dto.StoreResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "average_rating": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "total_reviews": {
                    "type": "integer"
                }
            }
        },
        "dto.UpdateReviewRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "rating": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Review": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/models.User"
                },
                "author_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ReviewImage"
                    }
                },
                "rating": {
                    "type": "number"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ReviewStatus"
                },
                "store": {
                    "$ref": "#/definitions/models.Store"
                },
                "store_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ReviewImage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "review_id": {
                    "type": "string"
                },
                "storage_key": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.ReviewStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected"
            ],
            "x-enum-varnames": [
                "ReviewStatusPending",
                "ReviewStatusApproved",
                "ReviewStatusRejected"
            ]
        },
        "models.Store": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "auto_created": {
                    "type": "boolean"
                },
                "average_rating": {
                    "type": "number"
                },
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "rejection_reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.StoreStatus"
                },
                "total_reviews": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.StoreStatus": {
            "type": "string",
            "enum": [
                "pending",
                "approved",
                "rejected"
            ],
            "x-enum-varnames": [
                "StoreStatusPending",
                "StoreStatusApproved",
                "StoreStatusRejected"
            ]
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "problem.Details": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "services.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "services.ReviewListResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReviewResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/services.Pagination"
                }
            }
        },
        "services.StoreListResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StoreResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/services.Pagination"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "杭电点评 API",
	Description:      "这是一个简单的校园点评网站的后端 API 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
